### ISSUE TITLE
help: Using fontaine with Google Fonts

### ISSUE THREAD

**Issue by ymansurozer** [nuxt-modules/fontaine#108]
### 📚 What are you trying to do?

I'd like to use Fontaine with Google Fonts, for which I am using [Nuxt Google Fonts module](https://github.com/nuxt-community/google-fonts-module).

When you say:
> If you are using a Google font or you don't have a @font-face declaration for a font you're using, you can declare them here.

Does this mean Fontaine does not work with Google fonts? Or is there a way to configure that?

### 🔍 What have you tried?

I reviewed the docs and the web but could not find a solution or anyone that encountered a similar problem.

**Comment by danielroe** [comment]
Yes, it should work fine with Google fonts. If you do not have any `@font-face` declarations in your _local_ CSS, such as if you are just directly pointing to a remote `.css` file, then you can add the font name you are using to the config option you've quoted.

**Comment by ymansurozer** [comment]
Thanks Daniel, I now see that the overrides are there when I build, awesome!

**Comment by nicoagp** [comment]
Does it work with Adobe Typekit font?

**Comment by danielroe** [comment]
Yes, it should.

**Comment by nicoagp** [comment]
Thank you @danielroe. I have looked into the docs and here but not able to find a working/demo example using google fonts or typekit.

is this the right way to use google fonts or typekit ?

```
  fontMetrics: {
    fonts: [
      'Lora', { family: 'Lora', src: 'https://use.typekit.net/upo0wpi.css' },
      'Source Sans 3', { family: 'Lora', src: 'https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap' },
    ],
  }
```

Thank you!
