### ISSUE TITLE
docs: more precisions in readme

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-modules/fontaine#131]
### 📚 Is your documentation request related to a problem?

I use Tailwind for my CSS. With it, you can have custom class to handle `font-family`.

So, in my CSS file, I write:

```scss
html {
  @apply font-<font-name>;
}
```

But this will not resolve in 
```
html {
  font-family: <font-name>, "<font-name> override";
}
```

But in 
```
html {
  font-family: <font-name>;
}
```

### 🔍 Where should you find it?

In the README, you say:

>  If you are using a Google font or you don't have a @font-face declaration
  for a font you're using, you can declare them here.

But maybe, you can add something about using `@apply` !

**Comment by mickaelchanrion** [comment]
You can specify the override in your tailwindcss config instead.
Example with Roboto: 
```js
fontFamily: {
   roboto: ['Roboto', 'Roboto override', 'sans-serif']
}
```

**Comment by Barbapapazes** [comment]
Yes, thank you!
