### ISSUE TITLE
help newb: how to generate overrides (content-wind + google-fonts + fontaine)

### ISSUE THREAD

**Issue by PatrikBird** [nuxt-modules/fontaine#145]
### 📚 What are you trying to do?

I'm trying to **integrate this module** + [Google Fonts module](https://github.com/nuxt-community/google-fonts-module) to [my website](https://github.com/PatrikBird/website) (which is based on [content-wind](https://github.com/Atinux/content-wind)).

I don't get any overrides generated, no matter what I try. I assume I don't understand the stack well enough, yet. 
Help very appreciated 🥲

### 🔍 What have you tried?

I've checked the issue https://github.com/nuxt-modules/fontaine/issues/108 and tried to specify the fontMetrics property in `nuxt.config.ts` (as I `do not have any @font-face declarations in my local CSS`):
```text
fontMetrics: {
  fonts: ['Poppins', { family: 'Poppins', src: '/assets/fonts/Poppins-400.woff2' }]
},
```
...not sure if that makes sense as I actually want to leverage the download option from the google-fonts module, but then I don't know how configure fontaine to generate overrides.

I also tried to specify `@font-face` in [my main.css](https://github.com/PatrikBird/website/blob/main/assets/css/main.css) instead of the lines above.

### ℹ️ Additional context

I set the font-family inside `tailwind.config.ts`
```
export default {
  theme: {
    fontFamily: {
      sans: ['Poppins', 'sans-serif']
    }
  }
}
```

**Comment by PatrikBird** [comment]
Still trying:

I removed the `fontMetrics` config object from my `nuxt.config.ts` and found some `Poppins override` after building within my bundle (at `server/chunks/app/server.mjs` and `public/_nuxt/entry.ec2f5241.css`, e.g.:
```
931:  useHead({ style: [{ 
children: css + ` @font-face { font-family: "Poppins override"; src: local("BlinkMacSystemFont"),
local("Segoe UI"),local("Roboto"),local("Helvetica Neue"),local("Arial"),local("Noto Sans"); 
ascent-override: 105%; descent-override: 35%; line-gap-override: 10%; }
[...]
```

still not sure if correct and if I set it up correctly as my CLS is unchanged.

**Comment by danielroe** [comment]
Apologies for this. With tailwind you will probably need to do this:

```js
export default {
  theme: {
    fontFamily: {
      sans: ['Poppins', 'Poppins override', 'sans-serif']
    }
  }
}
```

Let me know if that resolves things for you. 🙏

**Comment by PatrikBird** [comment]
Thanks for your quick reply! I really appreciate your work and that you're taking the time ❤️

I tried the tailwind cfg that you suggested:
- I **can** find `Poppins override` within the built bundle
- It's also shown in the browsers css tab `font-family: Poppins,Poppins override,sans-serif;`
- I did not specify the `fontMetrics` property in `nuxt.config.ts` and I **don't** declare @font-face in my local css (hope that's correct)

CLS seems still quite high/unchanged with ~0.221 -> it should be lower, no?

**Comment by danielroe** [comment]
Did you resolve this?

**Comment by Smef** [comment]
I found this in here and changing the tailwind config from using the `fallback` as in the docs term to `override` seems to have resolved this.

nuxt config
``` 
  fontMetrics: {
    fonts: ["Plus Jakarta Sans"],
  },
```

tailwind config:
``` 
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Plus Jakarta Sans override", ...fontFamily.sans],
      },
```

**Comment by Smef** [comment]
Whoops! Fixing my post:

It looks like `fallback` is what is being generated in the CSS for the font-face options. The sizing doesn't seem to match up, but  module is not using `override`.

The sizes don't seem to be calculating correctly, though, so while it is loading a fallback font, it's still shifting a whole bunch. In fact, it's even a bit worse than the default sans-serif, so I've disabled this.

I did see other posts about nuxt-fonts, so I'm going to check that out.

**Comment by danielroe** [comment]
Updated and released module with latest version of `fontaine`, which should resolve issue with the metrics being slightly off.

**Comment by Smef** [comment]
It stilld oesn't seem to have helped, unfortunately. I can confirm that fontaine 0.5.0 is installed, but the metrics are causing more CLS than the default. Here are some screenshots comparing the intended Jakarta font, the fontaine Fallback font, and the system UI font.

![font-jakarta](https://github.com/nuxt-modules/fontaine/assets/4460358/c27428e8-476f-467e-b56b-5290327cb4ae)
![font-fallback](https://github.com/nuxt-modules/fontaine/assets/4460358/fab19948-8d77-43b6-98c5-3c7cae81d048)
![font-ui-sans-serif](https://github.com/nuxt-modules/fontaine/assets/4460358/06d0e12f-70cb-4f40-984a-0c2d3fdfd6b5)
