### ISSUE TITLE
fix: inherit is also "inherit override"

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-modules/fontaine#155]
### 🐛 The bug

Using Unocss in a nuxt project, buton get "inherit override".

![image](https://user-images.githubusercontent.com/45267552/213394634-08165c74-1fd3-4139-b528-157a2dd8ff52.png)

### 🛠️ To reproduce

https://stackblitz.com/edit/github-zvbtmv?file=pages/index.vue

### 🌈 Expected behaviour

I expected that did not happened and to have only "inherit"

**Comment by zanfee** [comment]
I have stumbled across the same bug also using UnoCSS and Nuxt. This did not happen in the playground of the core fontaine repository.
Here is another reproduction which I made before finding this issue: https://stackblitz.com/edit/github-cltkj9?file=app.vue
