### ISSUE TITLE
Error Cannot start nuxt:  ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by narr07** [nuxt-modules/fontaine#210]
### 📚 What are you trying to do?

I have custom font

### 🔍 What have you tried?

And configured on tailwind.css

### ℹ️ Additional context

`[uncaughtException] Cannot destructure property 'capHeight' of 'font' as it is undefined. `

`Cannot start nuxt:  ENOENT: no such file or directory,`

`(node:2908) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously`

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏
