### ISSUE TITLE
fix: defineNuxtPlugin is not defined

### ISSUE THREAD

**Issue by yottybyte** [nuxt-modules/fontaine#235]
### 🐛 The bug

If you disable auto imports in the config, then an error occurs defineNuxtPlugin is not defined

### 🛠️ To reproduce

https://stackblitz.com/edit/github-yp6ihk?file=nuxt.config.ts

### 🌈 Expected behaviour

To avoid this error

**Comment by danielroe** [comment]
As it happens, this was already resolved but not released. Should now be good to go in v0.2.5.
