### ISSUE TITLE
fix: I can't get the same font into the override

### ISSUE THREAD

**Issue by amoralesdesign** [nuxt-modules/fontaine#278]
### 🐛 The bug

My goal is that fontaine makes an override with the same font, so that the same typography is always maintained, in this case: Signika.

I have the font in my local folder, I don't use Google fonts with url. 

Well, I can't get the override of Signika to be Signika itself, nuxt/fontaine adds me the overrides with some random local fonts.

**This is my font-face in the css file:**
`  /* latin-ext */
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('/assets/fonts/signikasemiboldlatinext.woff2') format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('/assets/fonts/signikasemiboldlatin.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }

  /* latin-ext */
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('/assets/fonts/signikaboldlatinext.woff2') format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-display: swap;
    font-weight: 700;
    src: url('/assets/fonts/signikaboldlatin.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }
`

**And this is the result of compiling the css with nuxt/fontaine (you are looking at the result of global.css from chrome debugger):**
 /* latin-ext */
  @font-face {
  font-family: "Signika override";
  src: local("BlinkMacSystemFont"),local("Segoe UI"),local("Roboto"),local("Helvetica Neue"),local("Arial"),local("Noto Sans");
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('/_nuxt/assets/fonts/signikasemiboldlatinext.woff2') format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
  font-family: "Signika override";
  src: local("BlinkMacSystemFont"),local("Segoe UI"),local("Roboto"),local("Helvetica Neue"),local("Arial"),local("Noto Sans");
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('/_nuxt/assets/fonts/signikasemiboldlatin.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }
  /* latin-ext */
  @font-face {
  font-family: "Signika override";
  src: local("BlinkMacSystemFont"),local("Segoe UI"),local("Roboto"),local("Helvetica Neue"),local("Arial"),local("Noto Sans");
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('/_nuxt/assets/fonts/signikaboldlatinext.woff2') format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
  font-family: "Signika override";
  src: local("BlinkMacSystemFont"),local("Segoe UI"),local("Roboto"),local("Helvetica Neue"),local("Arial"),local("Noto Sans");
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-display: swap;
    font-weight: 700;
    src: url('/_nuxt/assets/fonts/signikaboldlatin.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }

**And this is my nuxt.config, which nuxt/fontaine ignores anything I write in it about fonts:**

    fontMetrics: {
        fonts: [
          {
            family: 'Signika',
            fallbacks: ['Signika'],
            overrideName: 'fallback-signika',
            src: '/fonts/signikasemiboldlatin.woff2',
            root: 'assets',
          },
        ]
    },

### 🛠️ To reproduce

https://stackblitz.com/github/nuxt-modules/fontaine/tree/main/playground?file=package.json

### 🌈 Expected behaviour

Do you understand what I mean? I was hoping that in with slow 3g loads nuxt fontaine would keep me the same source, not change Signika for another one.
This is what I expected nuxt/fontaine to do:
/* latin-ext */
  @font-face {
  font-family: "Signika override";
  src: url('/_nuxt/assets/fonts/signikasemiboldlatinext.woff2') format('woff2');
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('/_nuxt/assets/fonts/signikasemiboldlatinext.woff2') format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
  font-family: "Signika override";
  src: url('/_nuxt/assets/fonts/signikasemiboldlatin.woff2') format('woff2');
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('/_nuxt/assets/fonts/signikasemiboldlatin.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }
  /* latin-ext */
  @font-face {
  font-family: "Signika override";
  src: url('/_nuxt/assets/fonts/signikaboldlatinext.woff2') format('woff2');
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('/_nuxt/assets/fonts/signikaboldlatinext.woff2') format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
  font-family: "Signika override";
  src: url('/_nuxt/assets/fonts/signikaboldlatin.woff2') format('woff2');
  ascent-override: 94%;
  descent-override: 29.2%;
  line-gap-override: 0%;
}
  @font-face {
    font-family: 'Signika';
    font-style: normal;
    font-display: swap;
    font-weight: 700;
    src: url('/_nuxt/assets/fonts/signikaboldlatin.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }

### ℹ️ Additional context

I have kept stackblitz the same as playground because the same thing happens, the Poppins font changes to another font instead of always staying the same.
I thought the point of nuxt/fontaine was to keep the same font.

**Comment by danielroe** [comment]
The aim is that fontaine uses a font that is already installed on the user's computer, but adjusts it to match the web font. Then it takes effect before the web font downloads. It would have no effect if it kept the web font as `src` as it would never be applied in that case...
