### ISSUE TITLE
docs: What is the setup for @nuxtjs/google-fonts?

### ISSUE THREAD

**Issue by dietler** [nuxt-modules/fontaine#341]
### 📚 Is your documentation request related to a problem?

I am just wonder what the format should be when using the Nuxt Google Fonts module.

Is this correct?
![zzzz2023-10-25 08_44_47-nuxt config ts - meznu-builder (Workspace) - Nuxt23 - Visual Studio Code - Insid](https://github.com/nuxt-modules/fontaine/assets/654584/ae7758ad-86d7-40d0-87e8-a19d2aaa4a52)

### 🔍 Where should you find it?

Example in the readme near where it says 
`// If you are using a Google font or you don't have a @font-face declaration`
`// for a font you're using, you can declare them here.`
under Usage

**Comment by MCB-jra** [comment]
@dietler Hello, did you manage to figure this out? I am in the same situation where i want to use nuxtjs/google-fonts with fontaine. Is that syntax correct?

**Comment by danielroe** [comment]
If you provide a reproduction, I'll happily tweak it so it works for you.

**Comment by danielroe** [comment]
We now have a better option for both Google Fonts + Fontaine in the form of Nuxt Fonts, which resolves this issue.

https://github.com/nuxt/fonts
