### ISSUE TITLE
fix: `tag.innerHTML.replace is not a function` when no module config is provided

### ISSUE THREAD

**Issue by CernyMatej** [nuxt-modules/fontaine#350]
### 🐛 The bug

When the `fontMetrics` configuration is omitted in `nuxt.config.ts`, pages fail to render with the following error:
`[500] tag.innerHTML.replace is not a function`.

### 🛠️ To reproduce

https://stackblitz.com/edit/github-rbztbr?file=nuxt.config.ts

### 🌈 Expected behaviour

No error should be thrown in the absence of `fontMetrics` in `nuxt.config.ts`

**Comment by harlan-zw** [comment]
Fixed upstream in Unhead 1.8.6.

**Comment by danielroe** [comment]
I think this should be fixed in `fontaine` now :+1:
