### ISSUE TITLE
fix: Node error

### ISSUE THREAD

**Issue by Schllimazll** [nuxt-modules/fontaine#375]
### 🐛 The bug

After install module on nuxt 3 Node start throwing error "(node:16336) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead. Use node --trace-deprecation ... to show where the warning was created)".
The error itself is not a problem, but it is still annoying when it appears in the console during each build. The error appeared after upgrading from version v20.11.0 to v21.6.1

### 🛠️ To reproduce

I can't give a link

### 🌈 Expected behaviour

Can with resolve this error?

**Comment by danielroe** [comment]
It is a dependency of `eslint` and needs to be resolved there. It's not related to this module.
