### ISSUE TITLE
fix: no fallback font on nuxt compatibility version 4

### ISSUE THREAD

**Issue by itsmnthn** [nuxt-modules/fontaine#418]
### 🐛 The bug

The fallback font is gone and CLS is back, wen adapting new dir structure with nuxt `future: { compatibilityVersion: 4,  },`

### 🛠️ To reproduce

https://stackblitz.com/edit/github-eevtp4?file=app%2Fpages%2Findex.vue

### 🌈 Expected behaviour

Should work as expected, generate fallback font and reduce CLS caused by fonts

**Comment by itsmnthn** [comment]
This was browser issue, local site as well as reproduction was causing late font loading for some reason, restarting browser fixed the issue. 

Not a module issue.

**Comment by danielroe** [comment]
whew!
